version: '2.0.0-{build}'
branches:
  only:
    - master
    - develop
image: Visual Studio 2017
clone_depth: 1
environment:
  Qt5_DIR: C:\Qt\5.12.2\msvc2017_64\
  VCINSTALLDIR: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\
build_script:
  - ps: scripts\build.ps1
after_build:
  - ps: scripts\package.ps1
artifacts:
  - path: '*.zip'
